### PR TITLE
Making descText and confirmText not required for ConfirmDeleteQueueModel

### LINKED ISSUE #79: Fix confirm modal PropTypes
`ConfirmDeleteQueueModal` and friends currently use the same propTypes as `ConfirmModal`, but they should only use a subset since `descText` and `confirmText` are never provided as props to those components.

### PR DESCRIPTION
**Pull request by PradyumnaShome**
Solved with @josh-byster and @jrogge.
Fixes #79.

### CODE REVIEW

**Comment by nwalters512** [comment]
So, this applies to the rest of the `Confirm...` modals as well. If you could make this change for the other modals as well and add a changelog entry, this should be set 👍

**Comment by nwalters512** [comment]
You can just edit `Changelog.md`, following the existing format.

**Comment by josh-byster** [comment]
I'm going to try working on this now to see if I can finish this up so we can be ready to merge :)

**Comment by nwalters512** [comment]
Closing in favor of #130

**Pull request closed without merging**
