### PR TITLE
Add last on duty staff leaving alert

### PR DESCRIPTION
**Pull request by AlpriElse**
Added requested from Issue [#146](https://github.com/illinois/queue/issues/146).

Added [Sweet Alert](https://sweetalert2.github.io/) library to dependencies.

capture

### CODE REVIEW

**Comment by AlpriElse** [comment]
Low key have never used a linter before today, sorry about the number of commits (didn't realize I could lint on my end and not have to rely on the pr checks).

**Comment by nwalters512** [comment]
Thanks for the PR! Is there any reason you opted to pull in a new dependency versus using a Bootstrap modal? We use those pretty extensively throughout the app.

**Comment by AlpriElse** [comment]
I noticed you guys use modals, specifically there is component called "Confirm Modal". But, I can't pass props to change the "Are you sure message?" to something desired for this, meaning a whole new component, for a modal that's a dependency to once, would need to be made. I used Sweet Alert to make the feature addition more trivial and reduce added complexity in the project.

Just let me know if you want this reimplemented by creating a new component using modals.

**Comment by nwalters512** [comment]
@AlpriElse that's just a convenience component - it's nothing more than a nice wrapper around some Bootstrap components. In the interest of keeping bundle sizes down and aiming for a consistent visual style, I'd prefer to stick with the Bootstrap modals!

**Comment by AlpriElse** [comment]
Reimplemented using modals. Needed to convert functional component to class to have state (following design pattern/usage of ConfirmModal). 

capture

**Pull request merged**
