### PR TITLE
Refine dark mode

### PR DESCRIPTION
**Pull request by nwalters512**
* Extend styles with slightly tweaked colors for buttons, alerts, etc. based on [DashKit](https://themes.getbootstrap.com/product/dashkit-admin-dashboard-template/).
* Add a page for admins where they can preview how a variety of Bootstrap components look with our themes.
* Use explicit path for darkmode cookie to avoid differing settings between pages.

### CODE REVIEW

**Comment by jackieo5023** [comment]
I just realized this is on master too, but when you create a queue, the text shows up as white, as well as the background when choosing a course.
image

**Comment by nwalters512** [comment]
Never caught that because Chrome on macOS with system-wide dark mode enabled displays things differently. I can reproduce on Firefox though. I'll see if I can tie #253 into the fix for that.

**Comment by nwalters512** [comment]
oops just realized I forgot a changelog entry. you failed the test 😛

**Comment by jackieo5023** [comment]
AHHH NOOO

**Pull request merged**
