### PR TITLE
Brand customization

### PR DESCRIPTION
**Pull request by winstan**
This provides a mechanism to configure Queue for a different institution via the environment variables INSTITUTION_LABEL and NETID_LABEL.

### CODE REVIEW

**Comment by nwalters512** [comment]
This was implemented in more depth in https://github.com/illinois/queue/pull/288 - would you like to assist with reviewing that PR? cc @james9909 - can you give more context on https://github.com/illinois/queue/pull/283? It looks like that was merged, but I can't find any commits for it on master.

**Comment by james9909** [comment]
@nwalters512: the content in #288 is the same as #283. We reverted master and re-opened the PR because when the deploy broke, we still wanted others to develop and merge onto a working master until Wade got a chance to redeploy.

**Comment by nwalters512** [comment]
@james9909 gotcha - is there any more work needed before it can be merged again? Would you be able to champion that branch and see it through to being merged?

**Comment by james9909** [comment]
@nwalters512 - we're waiting for when @wadefagen's ableto set up a clone of the queue on prod. Since I tested everything out on staging without issues, it *should* be fine but we want to test it out before merging.
Don't worry, I'm still pushing to get it merged :)

**Comment by winstan** [comment]
@nwalters512: #288 is missing the institution name customization in this PR, as well as the use of environment variables for customization.
I'm happy to help... Maybe I could help #288 through and then update this PR to just add institutionName to publicRuntimeConfig in next.config.js?
(Cinda is eager to get Queue working at UBC as soon as possible...)

**Comment by winstan** [comment]
There, in lieu of #288, I've ripped out the NetID changes from this PR.
Now this PR just parameterizes institution name, and does it using publicRuntimeConfig like in #288.

**Comment by winstan** [comment]
Now that #228 is merged, I've rebased this. It's all ready to go...

**Pull request merged**
